"""Assemble a Korean factual report exclusively from sealed CPU reductions."""
import csv,collections,os,json
from reducer import *
def rows(n):return list(csv.DictReader((REPORT/n).open()))
def cell(x):
    if x is None or x=='':return 'NOT_RECORDED'
    if isinstance(x,float):x=f'{x:.6g}'
    return str(x).replace('|','&#124;').replace('\n',' ')
def table(headers,data):
    return '\n'+'| '+' | '.join(headers)+' |\n| '+' | '.join(['---']*len(headers))+' |\n'+''.join('| '+' | '.join(cell(x) for x in row)+' |\n' for row in data)+'\n'
def num(x):return float(x) if x not in ['',None] else None
def main():
    final=rows('first-final-table.csv');sel=rows('selection.csv');mech=rows('mechanism-summary.csv');paired=rows('paired.csv');perf=rows('performance.csv');ret=rows('retention.csv');alloc=rows('allocation.csv');cost=rows('actual-cost.csv');prune=rows('pruning-summary.csv');native=rows('native-target-summary.csv');cand=rows('candidate.csv')
    audit=load(REPORT/'audit-summary.json');art=load(REPORT/'artifact-summary.json');cs=load(REPORT/'cost-summary.json');population=load(REPORT/'population-summary.json')
    conf=[
      ('공통 cold 시작','runtime.py:38–98; runner.py:29–35','COMMON_COLD_STATE/COLD_AND_LOCK/P_CONTEXT_RNG_FIXED','6 arm start W/M/P/context/RNG hash 동일; W0와 zeroM는 저장 runtime guard+공통 capsule','STORED_EVIDENCE_CONSISTENT','현재 model/W/M 실물 독립 재로드 없음'),
      ('native 동일 연산','native.py:105–154; fitting.py:23–160','FROZEN_SOURCE_COMMIT/FIT_STATE_CONFINEMENT','BLUE 원 AST fit/history 분리, L2=1/lr=.1/decay=.5/clamp=.75/KL=.0625/25loss·24Adam','SOURCE_CONFIRMED + STORED_EVIDENCE_CONSISTENT','CPU55,200 target capture 검산은 모델 재실행 아님'),
      ('prefix local-z 및 cache','controller.py:258–326; runtime.py:193–234','NATIVE_PREFIX_EVENT_BINDING/CACHE_KEY_WAS_FITTED','fit input/output 실제 상태와 ledger cache key 결속; 같은 prefix의 layer fit만 재사용','STORED_EVIDENCE_CONSISTENT','전체 weight 미보존으로 fractional endpoint 독립 재구성 불가'),
      ('gate0/1/중간 FP32','runtime.py:23–33; controller.py:258–326','ACTUAL_SUPPORT_FROM_WEIGHT_HASH','0 skip, 1 exact native copy, 중간 FP32 U+a(V−U); L5–7 포함','SOURCE_CONFIRMED + STORED_EVIDENCE_CONSISTENT','CPU hash는 GPU off/on parity 대체 아님'),
      ('E/H/B와 보호 ID','metrics.py:36–137; controller.py:342–366','ONLINE_REDUCTION/STRICT_PAIR_AGGREGATION/FEASIBILITY_EXACT_IDS','E token→native context→request; H canonical; B full-vocab W0 KL; exact strict/pair subset','STORED_EVIDENCE_CONSISTENT','평균 E 보호는 모든 요청 NLL·PS·NS 보호가 아님'),
      ('global min/tie','controller.py:512–520; analysis/audit.py:reasons/choose','INDEPENDENT_SELECTOR','전 실제 feasible pool Bmin+1e-6, ownN4→actual support→concat norm→gate lex→SHA;60/60 일치','STORED_EVIDENCE_CONSISTENT','국소 탐색 pool 안 선택이며 global optimum 아님'),
      ('F48 고정 예외','controller.py:665–672','INDEPENDENT_SELECTOR','(.75,.5) 10/10 raw commit; guard 탈락에도 ownN4로 교체하지 않음','STORED_EVIDENCE_CONSISTENT','F48 infeasible는 승인된 fixed 정책 관측이지 기술실패 아님'),
      ('legacy COBYLA','controller.py:614–644; execution.lock dependencies','FROZEN_SOURCE_COMMIT + SEARCH_STOP ledger','SciPy1.15.3; u=1−a/u0=0/rhobeg.25/tol.01/catol1e-8/maxiter64; E/H·pair .05는 단위','SOURCE_CONFIRMED + STORED_EVIDENCE_CONSISTENT','tol은 loss 허용치 아님; budget stop 수렴 증거 아님'),
      ('bounds/score 공유','controller.py:468–499','RAW_BOUNDS_GPU0/CACHE_KEY_WAS_FITTED','raw u bounds 먼저 검사; GPU0/dummy1/no clip; objective·constraint 동일 raw u 점수 공유','STORED_EVIDENCE_CONSISTENT','adaptive 호출 permutation invariance를 추가 요구하지 않음'),
      ('phase budget/미완료','controller.py:279–321,421–437','BUDGET_LIMITS/WHOLE_FIT_RESERVATION/ADAM_REFUND/INCOMPLETE_NOT_SCORED','search32+prune reserve8; score24+4; extraAdam9600; fit2400 reserve 후 actual 차감','STORED_EVIDENCE_CONSISTENT','pruning 전용 Adam reserve 없음; budget 미완료는 층 필요성 증거 아님'),
      ('exact-zero pruning','controller.py:522–555','PRUNING ledger + pruning-summary.csv','8→7→6→5 한 번씩, incumbent nonzero 추가층만, L4 pruning0, 글로벌 재선택','STORED_EVIDENCE_CONSISTENT','연속 a4=0 경계와 L4 pruning을 구분'),
      ('Past64 received-event','runner.py:46–50; local_z policy.py:27–37','PAST64_RECEIVED_HASH_PRIORITY','latest raw subject/relation, 현재 overwrite 제외, 고정 SHA priority, B1empty/후속64','STORED_EVIDENCE_CONSISTENT','성공 filtering0; all1000을 accepted-only로 바꾸지 않음'),
      ('observer 분리','runner.py:57–96; runtime.py:172–173','POSTSEAL_CONTROLLER_QUIET/CANDIDATE_OBSERVER_SEAL/ONLINE_INPUT_SEPARATION','선택·다음 state 결정 먼저 봉인, official P/N·Dev 이후; scope 밖 후보완성0','SOURCE_CONFIRMED + STORED_EVIDENCE_CONSISTENT','관측 함수 호출순서를 저장참조와 source로 확인; 모델 replay 없음'),
      ('history/다음 entry','runtime.py:252–264; runner.py:99–117','HISTORY_ALL5_ONCE/HISTORY_LAYER_HASH/ENTRY_LINK','60commit/300append/54인접link, selected endpoint에서 모든5층 whole100 key append1','STORED_EVIDENCE_CONSISTENT','zero gate·미사용층도 history 갱신; 기록 hash 검산과 M tensor 재구성 구분'),
      ('실제 tensor 수준','runtime.py:224–232; artifacts.py','CPU_WEIGHTS_ONLY_SCHEMA_FINITE_CAPTURE_COUNTERS_PASS','552 native files target/anchor/radius/key/readout/capture finite 및 카운터 검산','CPU_STORED_TENSOR_PASS','W/M checkpoint0; exact crash-resume NOT_AVAILABLE; GPU continuation NOT_TESTED'),
    ]
    csvout('source-conformance.csv',[dict(requirement=a,source=b,check=c,evidence=d,status=e,limit=f) for a,b,c,d,e,f in conf])
    text='# Sequential Local-z Allocation v2 — 여섯 cold arm 완료 상세 사실 리뷰\n\n'
    text+='상태: **6/6 scheduler COMPLETED(0:0), 6/6 실제 W10/1000 terminal 및 저장근거 CPU 검산 완료**. 신규 GPU 0. 과학적 우열·인과 기여·후속 정책의 판정은 이 SH 보고의 범위가 아니다.\n\n'
    text+='## 1. 실행 범위·읽기 기준과 검증 수준\n\n'
    text+='동일 fixed first1000의 여섯 cold W0/zeroM4..8 chain, 각 B100×10이다. 실제60batch/6000 arm-request observations이며 unique request는1000이다. 다른 실험의 N4/CAKE/repair/기존 cold7은 새 주표를 대체하지 않았고 해당 task를 재개하지 않았다.\n\n'
    text+='실행 `21297ec19e7f5aecec16d2fdb14cc79380a1df94` / tree `26be0758ee75503161c7cafffdec8397e6cf8165`; archive `c97083a1e1039c059b082bcf0ad0de1143bbfbe41a26be1db5c5d7a1bf54a7a8`; lock `a41cb76a25ab98b02c043397cd9cf4db0768e9ae312931b349008c3e9b303d18`. 제출·인계 publication `38fe0d39`, 이번 분석 시작 main `3658b7b4`와 다르다. Analysis source/현재 publication은 analysis-manifest 및 rooted receipt에 별도 결속한다.\n\n'
    text+='과거 2026-09-17T07:16:03Z의 agent 관측은 여섯 main PENDING/Resources·initial 미관측이었다. 이번에 읽은 initial-gate.json은 사후 저장 증거이며 그때 실시간 PASS였다고 소급하지 않는다. 지정6job만 한 번 sacct 조회했고 다른 job/실험 자료·live output 모니터링은 하지 않았다.\n'
    text+=table(['Arm','Array / 실제Job','상태/exit','시작(KST)','종료(KST)','할당 GPU초'],[[r['arm'],r['array_id']+' / '+r['physical_job_id'],r['state']+' '+r['exit'],r['start_KST'],r['end_KST'],r['allocated_GPU_seconds']] for r in alloc])
    text+='공통 model revision `8afb486c1db24fe5011ec46dfbe5b5dccdb575c2`, FP32/eager, matmul·cuDNN TF32 off, seed20260916. C4 sampling seed20260915와 구분한다. Physical4..8→P asset0..4→singleton local0. Context text/token/RNG 및 teacher는 기존 cold capsule를 재사용했다. 대형 model/teacher tensor를 이번에 전량 재해시하거나 모델로 재검증하지 않았다. 작은 manifest/source/lock은 현재 SHA, 모델·teacher 실물의 수치 연결은 봉인 technical evidence 재사용 수준이다.\n\n'
    text+='Dataset SHA `3d7f5e31db47b23f3a281bb6fb447c2fb1776e3d4721cdfb5fe5c6f998f10ae1`; whole order `5b01356928ad2e2e46effad5a2c5621c87746b610992b7b92bf3ace16b6f5729`; first1000 `40fe1afb318a4a5da9630425213644a729a1e85fb4e78c18e9a4dcd2870eefdd`. 원 data/order는 source lock과 결속했고 모든 평가 row의 case/prompt/target 해시를 독립적으로 재계산했다.\n'
    text+='## 2. Actual W10 전체1000 — 첫 독립 표\n\nRS/PS는 new NLL < true NLL, NS는 true NLL < new NLL. 동점은 실패다. 분모1000/2000/10000, 모든 arm ties0. TF-strict와 token accuracy는 이 preference 지표와 별개다.\n'
    text+=table(['Arm','RS count / %','PS count / %','NS count / %','ΔN4 RS/PS/NS pp'],[[r['arm'],f"{r['RS_count']}/1000 · {float(r['RS_percent']):g}",f"{r['PS_count']}/2000 · {float(r['PS_percent']):g}",f"{r['NS_count']}/10000 · {float(r['NS_percent']):g}",'/'.join(f'{float(r[t+"_delta_N4_pp"]):+.2f}' for t in ['RS','PS','NS'])] for r in final])
    text+='![Actual W10 R/P/N](final-rpn.png)\n\n각 축은 차이를 읽기 위한 확대 범위이며0에서 시작하지 않는다. 첫 표 SHA `'+sha(REPORT/'first-final-table.csv')+'`. 첫 표의 당시 status는 state audit pending이라는 중간 provenance를 보존했다. 아래 audit-summary가 후속 전체 저장근거 검산 수준이다.\n'
    text+='## 3. 동일 문항 paired 차이와 반대 방향 결과\n\n표는 앞 arm−뒤 arm이다. Lost=뒤 arm 성공→앞 arm 실패, gained=그 반대. 모든 비교는 동일 원문항 identity다. Δdesired NLL 양수는 R/P에서 new NLL, N에서 true NLL의 악화다. 아래 CI는 1000 case cluster bootstrap(2000회, seed20260918)의 percentile95%로, 관련 R/P/N prompt를 독립표본으로 부풀리지 않는다. 한 fixed order의 기술적 불확실성 요약이며 보편적 비열화 증명이나 다중비교 보정된 확정효과가 아니다.\n'
    primary=['C4-N4','C48-C4','C48-F48','C48-G48','C45678-C48']
    text+=table(['비교','지표','lost/gained','Δpp','95% CI(pp)','Δdesired NLL 평균 / p99'],[[r['comparison'],r['metric'],r['lost']+'/'+r['gained'],num(r['delta_pp']),f"[{float(r['ci95_low']):.3f}, {float(r['ci95_high']):.3f}]",f"{float(r['delta_desired_nll_mean']):+.5f} / {float(r['delta_desired_nll_p99']):+.5f}"] for r in paired if r['comparison'] in primary])
    text+='예를 들어 C48−G48은 PS −1.10pp(lost35/gained13), NS +.82pp(lost120/gained202)다. C45678−C48은 PS +1.00pp(lost17/gained37), NS −.58pp(lost203/gained145)다. 반대 방향 값을 합산한 단일 성공점수로 숨기지 않는다. C48−G48은 탐색 범위/예산도 달라 연속성만의 인과효과가 아니다.\n\n'
    text+='전체 신규 arm−N4, strict lost/gained, true/new NLL 평균·p95·p99·최대, 요청별 악화 수는 [paired.csv](paired.csv)에 있다. Hash-only per-row 변이는 local `paired-row-changes.json`에 보존하며 누락 행·가상 joint 분포를 생성하지 않았다.\n'
    text+='## 4. 시점별 유지·소실·회복, strict 및 tail\n\nAt-write는 각 요청이 도착한 서로 다른 모델의 관측을 모은 것이며 W0 또는 한 final 모델이 아니다. W5 first500과 W10 same first500은 같은 집단의 시간상 전이; W10 last500은 다른 cohort다.\n'
    rs=[r for r in perf if r['view'] in ['W5_FIRST500','W10_FIRST500','W10_LAST500','POOLED_ATWRITE']]
    text+=table(['Arm','시점/집단','RS%','PS%','NS%'],[[a,v,*[num(next(r['percent'] for r in rs if r['arm']==a and r['view']==v and r['metric']==t)) for t in ['RS','PS','NS']]] for a in ARMS for v in ['POOLED_ATWRITE','W5_FIRST500','W10_FIRST500','W10_LAST500']])
    text+=table(['Arm','전이','지표','원분모','lost/gained','Δdesired NLL 평균/p99'],[[r['arm'],r['comparison'],r['metric'],r['n'],r['lost']+'/'+r['gained'],f"{float(r['delta_desired_nll_mean']):+.5f}/{float(r['delta_desired_nll_p99']):+.5f}"] for r in ret if r['comparison'] in ['ATWRITE_TO_W10','W5_TO_W10_FIRST500']])
    fs=[r for r in perf if r['view']=='W10_ALL1000']
    text+=table(['Arm','R TF-strict /1000','P TF-strict /2000','two-P strict /1000','N true TF-strict /10000'],[[a,*[next(r['strict_count'] for r in fs if r['arm']==a and r['metric']==t) for t in ['RS','PS']],next(r['two_P_strict'] for r in fs if r['arm']==a and r['metric']=='PS'),next(r['strict_count'] for r in fs if r['arm']==a and r['metric']=='NS')] for a in ARMS])
    text+='Native/TF argmax의 tie는 원 torch 첫 token-index 규칙이며 preference NLL 동점 실패와 구분한다. Token 정확수/분모, true/new NLL·desired margin 중앙값/p95/p99/최대 및10cohort는 [performance.csv](performance.csv), 전이 tail은 [retention.csv](retention.csv).\n\n'
    text+=f"Received fact 기준 최종 ACTIVE {population['active']}, SUPERSEDED {population['superseded']}다. 합당한 동일 subject/relation overwrite를 단순 forgetting과 합치지 않았고 전체 requested1000을 주분모로 유지했다. Past64는 성공 기반이 아니다. 평가가 없는 batch 사이 정확한 최초 실패/회복 시점은 NOT_RECORDED다.\n"
    w=rows('w0-conditioned-ns.csv');text+=table(['Arm','W0 성공 N 분모','W10 유지 count/%'],[[r['arm'],r['n'],r['count']+' / '+r['percent']] for r in w])
    text+='## 5. 설계 → 실행 source → 저장 evidence\n\n검증 용어: SOURCE_CONFIRMED는 실제 executed bytes의 경로 확인, STORED_EVIDENCE_CONSISTENT는 저장 로그·해시·스칼라의 독립 산술 일치다. 이 둘을 새 model-level parity나 GPU continuation PASS로 승격하지 않는다.\n'
    text+=table(['요구사항','실제 함수/줄','실측/검사','수준·한계'],[[a,b,d,e+'; '+f] for a,b,c,d,e,f in conf])
    text+='각 source 줄은 frozen `21297ec` 기준이다. [source-inventory.csv](source-inventory.csv), [source-conformance.csv](source-conformance.csv), local audit-checks가 정확 SHA와 검사 이름을 결속한다.\n'
    text+='## 6. 탐색·채택·support·pruning 실제 동작\n\n매batch own We에서 mandatory full-L4 N4 한 번을 만든다. 후속 local-z/key/solve는 실제 앞층 gate를 적용한 prefix에서 계산한다. Own-N4는 자기 이전 trajectory의 누적 후속층도 유지하므로 독립 N4 sequential chain으로 복귀하는 것이 아니다. L4 fit을 앞 arm의 미래 direction으로 replay하지 않았다.\n'
    text+=table(['Arm','ownN4/10','선택 support1/2/≥3','완료후보/feasible','미완료','탐색 count proxy충족'],[[r['arm'],r['own_N4'],'/'.join(r[k] for k in ['selected_support1','selected_support2','selected_support3plus']),r['completed_candidates']+'/'+r['feasible_candidates'],r['incomplete'],r['coverage_adequate']+'/10' if r['coverage_applicable']=='True' else 'N/A fixed/grid'] for r in mech])
    text+='Support는 gate가 양수인 개수와 실제 entry 대비 W hash가 바뀐 층 수를 별도로 집계했다. [selected-gates.csv](selected-gates.csv)와 [candidate.csv](candidate.csv)에는 둘 다 있다. `action_norm`은 runtime의 actual concat ΔW FP64 Frobenius scalar다. 사후 W/M 미보존 상태에서 path/net/energy를 새로 재구성한 실측으로 만들지 않았다.\n\n![선택 gate](selected-gates.png)\n\n'
    text+='그림 숫자는 소수둘째자리 반올림이다. 표시1.00을 exact gate1로 읽지 않으며 정확한값은 CSV를 따른다. C4는 ownN4 8회, 나머지B6 a4=.9939162178/B8 .9925433527. G48은B2/B10에(.75,.5), 나머지8회ownN4. C48은B1 ownN4, B6/B8은 L4-only 연속계수, 나머지7회 L4/L8. C45678은B2/B5에 실제3층, B3/B4/B7/B10에2층, B1은 a4=.9982652821 단층, B6/B8/B9 ownN4다. C45678의 L7/L8 선택은0회다. 이는 조사된 pool의 선택 사실이지 해당 층의 불필요성/전역 support 최적성 증거가 아니다.\n'
    text+=table(['Arm/B','search vectors / unique endpoints / distinct a4','stop','extra fit/Adam','prune 시도/완료/삭제','prune완료?'],[[r['arm']+'/'+r['batch'],'/'.join(r[k] for k in ['completed_search_gate_vectors','completed_unique_state_tokens','distinct_a4']),r['stop'],r['suffix_fits']+'/'+r['extra_adam'],('/'.join(next(p[k] for p in prune if p['arm']==r['arm'] and p['batch']==r['batch']) for k in ['attempted','completed','deleted']) if r['arm'] in ['C48','C45678'] else 'N/A'),next((p['complete'] for p in prune if p['arm']==r['arm'] and p['batch']==r['batch']),'N/A')] for r in sel if r['arm'] in ['C48','C45678']])
    text+='연속30batch의 count proxy는 전부 충족했다(C4는 d1→3vector, C48 d2→최소4, C45678 d5→최소7 및 a4≥2). 실제 solver simplex나 수렴 인증이 아니다. C45678 전10batch SUFFIX_FIT_CAP; C48은 EXTRA_ADAM_RESERVE3/ENDPOINT_RESERVE1/SOLVER_RETURN6이다. 완료 후보만 score pool에 남겼고 불완전15개 비용은 보존했다. Pruning에서 Adam reserve가 부족한 경우를 층 삭제 실패의 품질 결론으로 쓰지 않는다.\n\n'
    text+='품질 판정은 E≤E_N4+1e-4, Past가 있으면 H≤H_N4+1e-4 및 각각 strict/pair exact-ID subset. `.05 plateau`는 없다. 수치 scale.05를 품질 allowance로 오해하지 않는다. [candidate.csv](candidate.csv)에 모든 후보의 E/H/B·ΔE/ΔB·lost ID 개수·탈락 이유·선택/phase가 남아 있고 원 ID집합·마진은 local raw에 있다.\n\n![저장된 후보 품질](candidate-quality.png)\n\n'
    text+='## 7. 대표 batch를 관측값으로 풀어 보기\n\n'
    for arm,b in [('C48','2'),('C45678','2'),('C45678','6'),('C45678','1')]:
        r=next(x for x in sel if x['arm']==arm and x['batch']==b);p=next(x for x in prune if x['arm']==arm and x['batch']==b)
        text+=f"### {arm} B{int(b):03d}\n\nown entry의 full L4는 E={float(r['raw_E']):.9g}, B={float(r['raw_B']):.9g}. 최종 gates `{r['gates']}`, actual support={r['support']}, concat ΔW norm={float(r['action_norm']):.8g}가 선택됐다. E={float(r['E']):.9g}(Δ{float(r['delta_E']):+.6g}), B={float(r['B']):.9g}(Δ{float(r['delta_B']):+.6g}). ownN4={r['own_n4']}; completed candidate={r['candidates']}, incomplete={r['incomplete']}; stop={r['stop']}. Prune 시도{p['attempted']}/완료{p['completed']}/삭제{p['deleted']}, 삭제층{p['deleted_layers']}. 이 선택 이후 같은 actual endpoint에서5층 history각1회, next ordinal={int(b)*100}으로 연결된다.\n\n"
    text+='OwnN4 선택은 그batch에서만 새L4 native endpoint를 선택한다는 뜻이며 이전 suffix의 누적분을 W0로 되돌리지 않는다. 저장된B1/B5/B10 ownN4→selected 공식 R/P/N 전이는 [own-n4-to-selected.csv](own-n4-to-selected.csv)다. 나머지batch의 ownN4 공식 P/N은 NOT_RECORDED이며 별도forward로 채우지 않았다. 후보 P/N은 이미 seal된 선택을 바꾸지 않는 same-entry 관측이고 가상 lifelong chain이 아니다.\n'
    text+='## 8. Native 최적화 계측·S64/Dev\n\nNative target55,200개를 모두 CPU weights_only로 읽어 request순서/target capture/anchor/radius/finite/Adam·loss·clamp counters를 검산했다. 아래 cap-stop은 마지막loss가 .05미만이 아니고25 loss budget으로 끝난 source stop label이다. 24step 도달을 target 학습 부족·수렴·capacity 증명으로 바꾸지 않는다. 추가 final gradient·KKT는 NOT_RECORDED.\n'
    nt=[]
    for a in ARMS:
        rr=[r for r in native if r['arm']==a];nt.append([a,*[sum(int(r[k]) for r in rr) for k in ['targets','zero_adam','cap_stop','loss_stop','clamp_hits']]])
    text+=table(['Arm','target calls','zero Adam','25-loss cap stop','loss<.05 stop','clamp events'],nt)
    text+='[native-target-summary.csv](native-target-summary.csv)에 arm/batch/layer별 native total/NLL/KL/decay 및 delta/radius 분포가 있다. Clamp event는 실제 trace횟수이며 최종 radius만 보고 추정한 값이 아니다. 동일 요청이 서로 다른 prefix에서 여러 번 native target을 만들므로 target calls는 unique 요청수와 다르다.\n'
    generic=rows('generic.csv');text+=table(['Arm','B5 S64 / Dev128','B10 S64 / Dev128'],[[a,*[' / '.join(f"{float(next(x['D'] for x in generic if x['arm']==a and x['batch']==str(b) and x['role']==role)):.8g}" for role in ['S64_SELECTED_ONLINE','Dev128_OBSERVER']) for b in [5,10]]] for a in ARMS])
    text+='S64는 selection online KL, Dev128은 독립 observer다. D의 감소를 canonical NS·true likelihood 향상 보장으로 동치화하지 않는다. Fixed W0 teacher192(기존98GPU초)는 재생성 없이 재사용했고 actual token/teacher 반복 연결의9단계READY는 technical49421의 저장 검증을 재사용했다. Report256/Audit/MMLU/FutureN은 NOT_MEASURED.\n'
    text+='## 9. 실제 비용·자원·저장\n\n'
    text+=f"신규6main 할당 합계 **{cs['new_science_allocated_GPU_seconds']:,} GPU초 ({cs['new_science_GPU_hours']:.6f} GPUh)**. 준비technical49421 **3379 GPU초**와 prior teacher98초는 별도이며 신규science에 중복청구하지 않는다. Exact six interval의 최대동시할당은2로 cap2와 일치한다. 다른task interval은 조회하지 않았고 제출 당시 admission evidence만 재사용한다. GPU allocation을 compute utilization으로 부르지 않는다.\n"
    text+=table(['Arm','할당GPU초','program wall초','target / Adam / loss / solve','online score / history','peak allocated GPU GiB'],[[a['arm'],a['allocated_GPU_seconds'],num(a['program_seconds']),'/'.join(next(c[k] for c in cost if c['arm']==a['arm']) for k in ['native_targets','native_Adam','native_loss','native_solves']),'/'.join(next(c[k] for c in cost if c['arm']==a['arm']) for k in ['online_scores','history_appends']),float(a['peak_GPU_allocated'])/2**30] for a in alloc])
    text+=table(['종류','계획상한','actual'],[[k,cs['planned_upper'][p],cs['total_actual'][k]] for k,p in [('native_targets','target'),('native_Adam','Adam'),('native_loss','loss'),('native_solves','solve'),('online_scores','score'),('history_appends','history')]])
    text+='Pure writer 및 state-I/O는 NOT_SEPARATED. Native-inclusive 안에 target/key/solve가 포함되고 online generic total 안에 teacherread가 포함되므로 합산하지 않는다. [actual-cost.csv](actual-cost.csv), [fit-cost.csv](fit-cost.csv), [score-cost.csv](score-cost.csv), [allocation.csv](allocation.csv)에 비중첩 invocation counters/단위가 있다. Official observer의 실제 F/B·token 합계는 별도 exact계수 NOT_RECORDED이며 raw panel 수를 forward수로 대체하지 않는다.\n\n'
    text+='Technical prior3379초 내부 nativeinclusive2315.1324초를 다시 더하지 않는다. 기술의 uninstrumented reference800target은 Adam/loss 미계측으로 보존했다. 과학 본실험552fit는 모두 계측됐다. No-update/ownN4 선택 및 rejected/incomplete 탐색 비용을 제외하지 않았다.\n\n'
    text+=f"현재 여섯 output의 fullSHA inventory는 **{art['files']:,}파일 / {art['bytes']:,}B**, native `.pt`552개다. W/M disk checkpoint는0이며 target/key/capture tensor만 CPU검산했다. 최초64GiB와 pilot후44GiB reserve는 예상계획이지 actual allocation이 아니다. Review 자체 출력은 원 과학 output과 분리하며 공유volume 변화의 원인을 이 실험으로 독점 귀속하지 않는다.\n"
    text+='## 10. 무결성·분석 한계와 재현\n\n'
    text+=f"Source/selector/state/metric 권한 검사는 최종 **{audit['checks']}개 / 실패{len(audit['failed'])}**다. 별도 red agent를 사용하지 않았고 SH4 자체 source audit와 runtime import 없는 독립 reducer/selector 재구현을 사용했다. CPU 검사 개수는 model correctness 확률이나 새로운GPU numerical gate PASS가 아니다.\n\n"
    text+='분석 r0에서는 prompt identity JSON의 ensure_ascii 및 ID집합 serialization의 numeric/lexical 정렬 차이를 처리하지 못했다. 원 source의 hash convention과 set semantics를 확인하여 새 분석 코드만 수리했다. 이전 r0 결과는 local audit-checks-analysis-r0-set-order.json에 보존했고 raw/source/threshold는 변경하지 않았다. Scalar와 margin 값 자체는 exact 일치 대조를 유지했다.\n\n'
    text+='최종 selected W/M 전체, 정확 crash-resume, independent GPU off/on/continuation은 각각 NOT_AVAILABLE / NOT_AVAILABLE / NOT_TESTED다. Hash-only commit/link는 기록된 chain 무결성 수준이다. 없는 tensor를 복원했다고 쓰지 않으며, 원 reviewer의 CPU재검산을 모델 재평가로 부르지 않는다. 원래 runtime hardguard가 지나간 증거와 사후 independent raw 산술은 구분한다.\n\n'
    text+='재현(새GPU/Slurm 호출 없음; bootstrap의 scheduler는 이미 한 번 봉인되어 재실행하지 않는다):\n\n```bash\nCUDA_VISIBLE_DEVICES=\'\' /data/janghj/EasyEdit/.venv/bin/python project/run_scripts/sequential_local_z_allocation/analysis/completed_review_20260918/reducer.py\npython3 project/run_scripts/sequential_local_z_allocation/analysis/completed_review_20260918/audit.py\nCUDA_VISIBLE_DEVICES=\'\' /data/janghj/EasyEdit/.venv/bin/python project/run_scripts/sequential_local_z_allocation/analysis/completed_review_20260918/performance.py\nCUDA_VISIBLE_DEVICES=\'\' /data/janghj/EasyEdit/.venv/bin/python project/run_scripts/sequential_local_z_allocation/analysis/completed_review_20260918/artifacts.py\nCUDA_VISIBLE_DEVICES=\'\' /data/janghj/EasyEdit/.venv/bin/python project/run_scripts/sequential_local_z_allocation/analysis/completed_review_20260918/synthesis.py\nCUDA_VISIBLE_DEVICES=\'\' /data/janghj/EasyEdit/.venv/bin/python project/run_scripts/sequential_local_z_allocation/analysis/completed_review_20260918/plot.py\npython3 project/run_scripts/sequential_local_z_allocation/analysis/completed_review_20260918/report.py\n```\n\n'
    text+='원 raw는 read-only. 코드의 ROOT/LOCAL/WT는 이 task의 봉인 S4 경로이며 다른 서버로 raw전송하지 않는다. [raw-inventory.csv](raw-inventory.csv), [analysis-manifest.json](analysis-manifest.json), [rooted-receipt.json](rooted-receipt.json), [publication-checks.json](publication-checks.json)이 산출물·검사·source lineage를 결속한다. PNG는 코드 생성, 실제 관측점만 사용했고 미측정 성능을 보간하지 않았다. HTML parser 렌더와 PNG 육안 확인 수준은 publication checks에 명시한다.\n\n완료후 TASK_COMPLETE_STOP / automatic_resume=false. 새로운 실험·후속 tuning·자동모니터링은 하지 않는다. NO_BROADCAST_NOT_REQUIRED.\n'
    (REPORT/'diagnostic-report-ko.md').write_text(text)
    finalv2=[dict(r,status='COMPLETED_1000_NLL_AND_STORED_CHAIN_CPU_VERIFIED') for r in final];csvout('final-table.csv',finalv2)
if __name__=='__main__':main()
